spring:
  application:
    name: company-service
  #  config:
  #    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888

spring.config.import: 'optional:configserver:'
