
server:
  port: 8082  # Уникальный порт для company-service

spring:
  application:
    name: company-service  # Имя сервиса для Eureka
#  config:
#    import: 'optional:configserver:'
#  cloud:
#    config:
#      uri: http://localhost:8888  # Подключение к Config Server
  datasource:
    url: jdbc:postgresql://localhost:5433/company_db  # Подключение к своей БД
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/  # Регистрация в Eureka